disabled_rules:
  - orphaned_doc_comment
  - trailing_whitespace

force_cast: warning 

identifier_name:
  excluded:
    - i
    - id
    - x
    - y
    - z
    - uv

line_length:
  warning: 130
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
